# Generated by Django 5.2 on 2025-05-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vault', '0003_uploadedfile_user_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='password_hash',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
